server:
  port: 9999
spring:
  datasource:
    username: 'root'
    password: '!Sungrow2011'
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter-class-names: stat,wall,log4j
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  cache:
    type: REDIS
  redis:
    host: 127.0.0.1
    password: sungrow2011
    port: 6379
    timeout: 10000 # 连接超时时间（毫秒）
    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8 # 连接池中的最大空闲连接 默认 8
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
logging:
  level:
    com.chengkun.cloud.mapper: debug
mybatis:
  #pojo别名扫描包
  type-aliases-package: com.chengkun.cloud.pojo
  #加载Mybatis映射文件
  mapper-locations: classpath:mapper/*Mapper.xml
  #开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true